server:
  servlet:
    context-path: /medicine
  port: 8088
logging:
  level:
    com.bonc.medicine: debug
    org.springfromework.web: info
    org.hibernate: error

spring:
  datasource:
    #name: test
    url: jdbc:mysql://192.168.1.21:3306/xuanjiuwei?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20

  redis:
    host: 192.168.1.20
    password: ~
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000

  data:
    elasticsearch:
      cluster-nodes: 192.168.1.24:9300
      cluster-name: es-cluster
      repositories:
        enabled: true


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  #type-aliases-package: com.bonc.parent.chineseherbalmedicine.entity
hbase:
  master: 192.168.1.24:6000
  zookeeper:
    quorum: hadoop003,hadoop004,hadoop005,hadoop006,hadoop007
    property:
      clientPort: 2181
zookeeper:
  znode:
    parent: /hbase

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

